name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Jeka congrats you for your first created issue!'' first issue'
        pr-message: 'Jeka congrats you for your first pull request :)'' first pr'
